### ISSUE TITLE
OGDSPEC: 404

### ISSUE THREAD

**Issue by skurzinz** [the42/ogdat#1]
The spec file is not available online any longer, cf.
https://github.com/the42/ogdat/blob/d667415d7fb71d953ae563bbe5251e742aa321f3/ogdatv23/getspec.sh#L5

**Comment by the42** [comment]
The latest specification is available for download as https://neu.ref.wien.gv.at/at.gv.wien.ref-live/documents/20189/68315/Metadaten_data.gv.at_2.5_fin.pdf/390eb5f4-e4e3-43e6-b4d4-805499c6b003

I doubt that this tool will work with the latest specification of which the canonical version is sadly PDF only.

I have no incentive to modernize or revive this project.
